workflows:
  ios-workflow:
    name: iOS Build & Test
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_PROJECT: "Cookpedia.xcodeproj"
        XCODE_SCHEME: "Cookpedia"

    scripts:
      - name: Run tests
        script: |
          xcodebuild test -project $XCODE_PROJECT \
          -scheme $XCODE_SCHEME \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest'
      - name: Build App
        script: |
          xcodebuild build -project $XCODE_PROJECT \
          -scheme $XCODE_SCHEME \
          -destination 'generic/platform=iOS'