workflows:
  ios-workflow:
    name: iOS Build & Test
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_PROJECT: "Cookpedia.xcodeproj"  # Assure-toi que ce fichier existe bien dans le repo
        XCODE_SCHEME: "CookpediaTests"        # Utilise bien le bon schéma de test
        XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest"

    scripts:
      - name: Debug environment variables
        script: |
          echo "XCODE_PROJECT: $XCODE_PROJECT"
          echo "XCODE_SCHEME: $XCODE_SCHEME"

      - name: Clean project
        script: |
          if [[ -z "$XCODE_PROJECT" || -z "$XCODE_SCHEME" ]]; then
            echo "ERROR: XCODE_PROJECT or XCODE_SCHEME is not set!"
            exit 1
          fi
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME"

      - name: Run tests
        script: |
          xcodebuild test -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          -destination "$XCODE_DESTINATION" \
          -enableCodeCoverage YES | xcpretty && exit ${PIPESTATUS[0]}