workflows:
  ios-workflow:
    name: iOS Build & Test
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_PROJECT: "Cookpedia.xcodeproj"
        XCODE_SCHEME_APP: "Cookpedia"
        XCODE_SCHEME_TESTS: "CookpediaTests"
        XCODE_DESTINATION: "platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest"

    scripts:
      - name: Clean project
        script: |
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME_APP"

      - name: Run tests
        script: |
          xcodebuild test -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME_TESTS" \
          -destination "$XCODE_DESTINATION" \
          -enableCodeCoverage YES | xcpretty && exit ${PIPESTATUS[0]}