workflows:
  ios-workflow:
    name: iOS Build & Test
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      vars:
        XCODE_PROJECT: "Cookpedia.xcodeproj"
        XCODE_SCHEME: "CookpediaTests"

      vars:
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY

    scripts:
      - name: Run tests
        script: |
          xcodebuild test -project $XCODE_PROJECT \
          -scheme $XCODE_SCHEME \
          -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest' \
          -enableCodeCoverage YES | xcpretty && exit ${PIPESTATUS[0]}
      - name: Build App
        script: |
          xcodebuild build -project $XCODE_PROJECT \
          -scheme Cookpedia \
          -destination 'generic/platform=iOS' \
          -allowProvisioningUpdates
      - name: Debug Build
        script: |
         set -o pipefail && xcodebuild build -project $XCODE_PROJECT \
         -scheme Cookpedia \
         -destination 'generic/platform=iOS' | tee build.log | xcpretty && exit ${PIPESTATUS[0]}